import React from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar/navbar";
import Footer from "../components/footer/footer";
import HeroImg from "../img/hero.png";
import {
  HeroContainer,
  HeroTitle,
  HeroBtnContainer,
  ServiceBtn,
  ProjectBtn,
  ImageWrap,
} from "../styles/index";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jonfoon-about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <HeroContainer>
        <ImageWrap>
          <Image src={HeroImg} alt="construction" />
        </ImageWrap>
        <HeroTitle>
          <h1>We Provide Effective World Class Solutions!</h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor
          </p>
          <HeroBtnContainer>
            <ServiceBtn>Our Services</ServiceBtn>
            <ProjectBtn>Recent Projects</ProjectBtn>
          </HeroBtnContainer>
        </HeroTitle>
      </HeroContainer>

      <Footer />
    </div>
  );
}
