import React from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar/navbar";
import Footer from "../components/footer/footer";
import HeroImg from "../img/about.png";
import Rectangle from "../img/Rectangle.png";
import CEO from "../img/ceo.jpeg";
import {
  HeroContainer,
  HeroBtnContainer,
  TalkToUsBtn,
} from "../styles/index";

import {
  AboutWrapper,
  AboutTitlecontainer,
  SectionTitle,
  AboutContentContainer,
  ContentCard,
  CardTitle,
  CardContent,
  TeamWrapper,
  TeamTtleContainer,
  TeamMemberCardContainer,
  TeamMember,
  TeamMemberImage,
  TeamMemberInfo,
  TeamMemberName,
  TeamMemberRole,
  ImageWrap,
  HeroTitle,
  HeroSubTitle
} from "../styles/about";

const About = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <HeroContainer>
        <ImageWrap>
          <Image src={HeroImg} alt="construction" />
        </ImageWrap>
        <HeroTitle>
          <HeroSubTitle>
            <h1 style={{ height: "auto", margin: 0 }}>About The Company</h1>
          </HeroSubTitle>
          <HeroBtnContainer>
            <TalkToUsBtn>Talk To Us</TalkToUsBtn>
          </HeroBtnContainer>
        </HeroTitle>
      </HeroContainer>

      <AboutWrapper>
        <AboutTitlecontainer>
          <SectionTitle>About Jonafoon</SectionTitle>
          <Image src={Rectangle} alt="rectangle" />
        </AboutTitlecontainer>
        <AboutContentContainer>
          <ContentCard>
            <CardTitle>Mission</CardTitle>
            <CardContent>
              At Jonafoon our mission is to ensure delivery of quality
              professional services abiding to high ethical standards with
              state- of-the-art technology and use of appropriate expertise and
              partnerships.
            </CardContent>
          </ContentCard>
          <ContentCard>
            <CardTitle>Vission</CardTitle>
            <CardContent>
              To be the most technological driven and advanced construction,
              engineering, and project management organization in Africa.uat.
            </CardContent>
          </ContentCard>
        </AboutContentContainer>
      </AboutWrapper>

      <TeamWrapper>
        <TeamTtleContainer>
          <SectionTitle>Our Team</SectionTitle>
        </TeamTtleContainer>
        <TeamMemberCardContainer>
          <TeamMember>
            <TeamMemberImage>
              <Image src={CEO} alt="Bolaji" />
            </TeamMemberImage>
            <TeamMemberInfo>
              <TeamMemberName>Bolaji Owupe</TeamMemberName>
              <TeamMemberRole>Chief Executive Officer</TeamMemberRole>
            </TeamMemberInfo>
          </TeamMember>
          <TeamMember>
            <TeamMemberImage>
              <Image src={CEO} alt="chief executive officer" />
            </TeamMemberImage>
            <TeamMemberInfo>
              <TeamMemberName>John Smith</TeamMemberName>
              <TeamMemberRole>Chief Executive Officer</TeamMemberRole>
            </TeamMemberInfo>
          </TeamMember>
          <TeamMember>
            <TeamMemberImage>
              <Image src={CEO} alt="Zakari" />
            </TeamMemberImage>
            <TeamMemberInfo>
              <TeamMemberName>Zakari .O. Osuman</TeamMemberName>
              <TeamMemberRole>Cybersecurity - Specialist</TeamMemberRole>
            </TeamMemberInfo>
          </TeamMember>
        </TeamMemberCardContainer>
      </TeamWrapper>

      <Footer />
    </div>
  );
}

export default About;