import React from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar/navbar";
import Footer from "../components/footer/footer";
import HeroImg from "../img/about.png";
import Rectangle from "../img/Rectangle.png";
import CEO from "../img/ceo.jpeg";
import {
  HeroContainer,
  HeroTitle,
  HeroBtnContainer,
  TalkToUsBtn,
  ImageWrap,
} from "../styles/index";

import {
  AboutWrapper,
  AboutTitlecontainer,
  SectionTitle,
  AboutContentContainer,
  ContentCard,
  CardTitle,
  CardContent,
  TeamWrapper,
  TeamTtleContainer,
  TeamMemberCardContainer,
  TeamMember,
  TeamMemberImage,
  TeamMemberInfo,
  TeamMemberName,
  TeamMemberRole,
} from "../styles/about";

const About = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <HeroContainer>
        <ImageWrap>
          <Image src={HeroImg} alt="construction" />
        </ImageWrap>
        <HeroTitle>
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "flex-end",
              height: "280px",
            }}
          >
            <h1 style={{ height: "auto", margin: 0 }}>About The Company</h1>
          </div>
          <HeroBtnContainer>
            <TalkToUsBtn>Talk To Us</TalkToUsBtn>
          </HeroBtnContainer>
        </HeroTitle>
      </HeroContainer>

      <AboutWrapper>
        <AboutTitlecontainer>
          <SectionTitle>About Jonafoon</SectionTitle>
          <Image src={Rectangle} alt="rectangle" />
        </AboutTitlecontainer>
        <AboutContentContainer>
          <ContentCard>
            <CardTitle>Mission</CardTitle>
            <CardContent>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </CardContent>
          </ContentCard>
          <ContentCard>
            <CardTitle>Vission</CardTitle>
            <CardContent>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </CardContent>
          </ContentCard>
        </AboutContentContainer>
      </AboutWrapper>

      <TeamWrapper>
        <TeamTtleContainer>
          <SectionTitle>Our Team</SectionTitle>
        </TeamTtleContainer>
        <TeamMemberCardContainer>
          <TeamMember>
            <TeamMemberImage>
              <Image src={CEO} alt="chief executive officer" />
            </TeamMemberImage>
            <TeamMemberInfo>
              <TeamMemberName>John Smith</TeamMemberName>
              <TeamMemberRole>Chief Executive Officer</TeamMemberRole>
            </TeamMemberInfo>
          </TeamMember>
          <TeamMember>
            <TeamMemberImage>
              <Image src={CEO} alt="chief executive officer" />
            </TeamMemberImage>
            <TeamMemberInfo>
              <TeamMemberName>John Smith</TeamMemberName>
              <TeamMemberRole>Chief Executive Officer</TeamMemberRole>
            </TeamMemberInfo>
          </TeamMember>
          <TeamMember>
            <TeamMemberImage>
              <Image src={CEO} alt="chief executive officer" />
            </TeamMemberImage>
            <TeamMemberInfo>
              <TeamMemberName>John Smith</TeamMemberName>
              <TeamMemberRole>Chief Executive Officer</TeamMemberRole>
            </TeamMemberInfo>
          </TeamMember>
        </TeamMemberCardContainer>
      </TeamWrapper>

      <Footer />
    </div>
  );
}

export default About;